name: Production Deploy

on:
  workflow_dispatch:
  release:
    types: [ released ]

env:
  SUPPLY_UPLOAD_MAX_RETRIES: 5

jobs:
  play_promote_production:
    name: Play Publish Production
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Fastlane
        run: |
          gem install bundler:2.2.27
          bundle install --jobs 4 --retry 3
          bundle exec fastlane add_plugin amazon_app_submission
          bundle exec fastlane add_plugin semantic_release    

      - uses: ./.github/actions/inflate-secrets
        name: Inflate Secrets
        with:
          keystore: ${{ secrets.KEYSTORE_FILE }}
          google-services: ${{ secrets.GOOGLESERVICES }}
          firebase-creds: ${{ secrets.FIREBASECREDS }}
          playstore-creds: ${{ secrets.PLAYSTORECREDS }}

      - name: Promote Beta to Production Play Store
        run: bundle exec fastlane promote_to_production